codehaus-plexus/plexus-utils

pom.xml
SCM info in plexus-utils 3.0.22-SNAPSHOT incorrectly points to plexus-compiler git repo.
See: http://jira.codehaus.org/browse/PLXUTILS-176
=> [PLXUTILS-176] Fix SCM info

src/main/java/org/codehaus/plexus/util/FileUtils.java, src/main/java/org/codehaus/plexus/util/IOUtil.java, src/test/java/org/codehaus/plexus/util/IOUtilTest.java
o Updated to stop suppressing exception's thrown when closing streams.
o Updated to correctly test for end of file conditions.
o Catching up with the following 'commons-io' bug fixes:
https://issues.apache.org/jira/browse/IO-298
https://issues.apache.org/jira/browse/IO-502
=> Various bug fixes for classes 'FileUtils' and 'IOUtil'.

src/main/java/org/codehaus/plexus/util/FileUtils.java
Since Plexus Utils enforces Java 7 it is safe to invoke NIO operations introduced by JRE 7. Among those operations are methods for potentially offloading work to the operating system. Theoretically this should be (much) faster on modern JREs than pumping bytes up and down the JVM just to get them from one file into another. Even without any actual performance gain it makes sense to get rid of custom code in favor of JRE code, as it improves class loading speed and reduces memory and
on-disk footprint, while cutting down number of potential bugs at the same time.
=> offloading file copy work to operating system allows potential speedup

src/main/java/org/codehaus/plexus/util/NioFiles.java
When A is an existing symlink to B, then createSymbolicLink(A,C) does neither overwrite A->B by A->C (as expected in analogy to the behavior of copy(A,C)) nor does it throw an exception nor does it return A->B to indicate the failure, but it actually "silently fails", i. e. it returns A->C!
This certainly is heavily problematic, unsymmetric to what copy(File,File) and Files.createSymbolicLink(Path,Path) do, and certainly unwanted and buggy behavior.
The solution is to delete any existing target before creating the symlic, hence copying the behavior of copy(File,File).
=> bug fix: silently fails overwriting symlinks

src/main/java/org/codehaus/plexus/util/xml/PrettyPrintXMLWriter.java, src/test/java/org/codehaus/plexus/util/xml/PrettyPrintXMLWriterTest.java
Changed concatenation expression in endElement() method to avoid the Java 7 bug.
Added test to detect if the bug is present.
=> #51: PrettyPrintXMLWriter fails with a java.util.NoSuchElementException (Java 1.7 only)

pom.xml, src/main/java/org/codehaus/plexus/util/xml/Xpp3Dom.java, src/main/java/org/codehaus/plexus/util/xml/Xpp3DomBuilder.java, src/main/java/org/codehaus/plexus/util/xml/Xpp3DomUtils.java, src/test/java/org/codehaus/plexus/util/xml/Xpp3DomBuilderTest.java, src/test/java/org/codehaus/plexus/util/xml/Xpp3DomTest.java, src/test/java/org/codehaus/plexus/util/xml/Xpp3DomUtilsTest.java
=> 61 input location

src/main/java/org/codehaus/plexus/util/cli/Commandline.java
Hi
In order to avoid such bad OS dependency code as below
```
String[] commandLine = cl.getCommandline();
if ( Os.isFamily( Os.FAMILY_WINDOWS ) )
{
if ( Os.isFamily( Os.FAMILY_WIN9X ) )
{
assertArrayEquals( new String[] { "command.com", "/C", "\"gcc -Ip1 -Ip2 -Isp1 -Isp2 -o object.o -c source.c\"" },  commandLine );
}
else
{
assertArrayEquals( new String[] { "cmd.exe", "/X", "/C", "\"gcc -Ip1 -Ip2 -Isp1 -Isp2 -o object.o -c source.c\"" },  commandLine );
}
}
else
{
assertArrayEquals( new String[] { "gcc", "-Ip1", "-Ip2", "-Isp1", "-Isp2", simpleArgv[0], simpleArgv[1],
simpleArgv[2], simpleArgv[3] }, commandLine );
}
```
this PR introduces the function `public String[] getRawCommandline()` so that the above code be reformated as
```
String[] commandLine = cl.getRawCommandline(); …
```
=> Add public String[] getRawCommandline() to avoid OS dependency code in unit tests

src/main/java/org/codehaus/plexus/util/FileUtils.java, src/test/java/org/codehaus/plexus/util/FileUtilsTest.java
New method `FileUtils.linkFile` does the same as `FileUtils.copyFile`, but instead of actually moving the file content, it just produces a symbolic link.
Unit tests are exactly the same as for `FileUtils.copyFile` but in addition check that the result is really a symlink.
=> new feature  FileUtils.linkFile(source, destination)

pom.xml
Signed-off-by: olivier lamy <olamy@apache.org>
=> avoid build issues with symlink

src/main/java/org/codehaus/plexus/util/xml/Xpp3Dom.java
Signed-off-by: olivier lamy <olamy@apache.org>
=> add removeAttribute method to Xpp3Dom

src/main/java/org/codehaus/plexus/util/Expand.java, src/main/java/org/codehaus/plexus/util/FileUtils.java, src/main/java/org/codehaus/plexus/util/PropertyUtils.java, src/main/java/org/codehaus/plexus/util/ReaderFactory.java, src/main/java/org/codehaus/plexus/util/WriterFactory.java, src/main/java/org/codehaus/plexus/util/xml/XmlReader.java, src/main/java/org/codehaus/plexus/util/xml/XmlStreamWriter.java, src/test/java/org/codehaus/plexus/util/FileBasedTestCase.java, src/test/java/org/codehaus/plexus/util/FileUtilsTest.java, src/test/java/org/codehaus/plexus/util/IOUtilTest.java, src/test/java/org/codehaus/plexus/util/xml/PrettyPrintXMLWriterTest.java, src/test/java/org/codehaus/plexus/util/xml/XmlUtilTest.java
This PR proposed the use of NIO-7 functionality to benefit from potential performance gains thanks to offloading to lower levels (JVM-internal solutions, OS-internal solutions, FS-internal solutions, etc.) instead of old-school File API.
=> NIO-7: Potential performance gains using offloading

.github/workflows/maven.yml
As we have recently pushed the minimum JRE version from 7 to 8, we must not build on JRE 7 anymore, as using any JRE 8 API would definitively break CI then!
=> Not building on JRE 7 anymore, since we pushed minimum to JRE 8

src/main/java/org/codehaus/plexus/util/xml/pull/MXParser.java, src/test/java/org/codehaus/plexus/util/xml/pull/IBMXML10Tests_Test_IBMXMLConformanceTestSuite_not_wftests_Test_IBMXMLConformanceTestSuite_Production32_Test.java, src/test/resources/xmlconf/ibm/not-wf/P32/ibm32n01.xml, src/test/resources/xmlconf/ibm/not-wf/P32/ibm32n02.xml, src/test/resources/xmlconf/ibm/not-wf/P32/ibm32n03.xml, src/test/resources/xmlconf/ibm/not-wf/P32/ibm32n04.xml, src/test/resources/xmlconf/ibm/not-wf/P32/ibm32n05.xml, src/test/resources/xmlconf/ibm/not-wf/P32/ibm32n06.dtd, src/test/resources/xmlconf/ibm/not-wf/P32/ibm32n06.xml, src/test/resources/xmlconf/ibm/not-wf/P32/ibm32n07.xml, src/test/resources/xmlconf/ibm/not-wf/P32/ibm32n08.xml, src/test/resources/xmlconf/ibm/not-wf/P32/ibm32n09.dtd, src/test/resources/xmlconf/ibm/not-wf/P32/ibm32n09.xml
- fixed the bug.
- removed unused requireNextS() method.
=> Fix MXParser failing to parse properly 'standalone' declaration attribute (#130)

src/main/java/org/codehaus/plexus/util/xml/pull/MXParser.java, src/test/java/org/codehaus/plexus/util/xml/pull/IBMXML10Tests_Test_IBMXMLConformanceTestSuite_not_wftests_Test_IBMXMLConformanceTestSuite_Production32_Test.java, src/test/java/org/codehaus/plexus/util/xml/pull/IBMXML10Tests_Test_IBMXMLConformanceTestSuite_not_wftests_Test_IBMXMLConformanceTestSuite_Production80_Test.java, src/test/resources/xmlconf/ibm/not-wf/P80/ibm80n01.xml, src/test/resources/xmlconf/ibm/not-wf/P80/ibm80n02.xml, src/test/resources/xmlconf/ibm/not-wf/P80/ibm80n03.xml, src/test/resources/xmlconf/ibm/not-wf/P80/ibm80n04.xml, src/test/resources/xmlconf/ibm/not-wf/P80/ibm80n05.xml, src/test/resources/xmlconf/ibm/not-wf/P80/ibm80n06.xml
Fix MXParser do not fail when the leading white space is missing in the EncodingDecl in the XMLDecl (file not-wf/P80/ibm80n01.xml) (#134)
=> Fix MXParser do not fail when the leading white space is missing (#134)

src/main/java/org/codehaus/plexus/util/xml/pull/MXParser.java, src/test/java/org/codehaus/plexus/util/xml/pull/IBMXML10Tests_Test_IBMXMLConformanceTestSuite_not_wftests_Test_IBMXMLConformanceTestSuite_Production32_Test.java, src/test/java/org/codehaus/plexus/util/xml/pull/MXParserTest.java
- Fix bugs.
- Added tests.
- Improved error messages.
=> Fix MXParser fails to parse xml declaration properly (#138)

.github/workflows/maven.yml
Since JDK 16 is generally available it makes no sense to use an early access build anybody.
=> Using JDK 16 GA instead of JDK 16 EA

pom.xml
Enforcing the use of JDK 11 on release guarantees that the published Multi-Release JAR contains ALL code versions: JDK 8 (default fallback), JDK 9 (enhanced NIO) and JDK 10 (even further enhanced NIO). Without this enforcement, there would be a risk of not having some of these versions packed into the MRJAR due to the way the POM checks for the existence of supported JDK levels using JDK-enabled profiles.
This PR was requested by @olamy in https://github.com/codehaus-plexus/plexus-utils/pull/120#issuecomment-813327648, and is effective only in the `plexus-release` profile as requested by @rfscholte  in https://github.com/codehaus-plexus/plexus-utils/pull/148#discussion_r607186506. While it technically would be _enough_ to just enforce JDK 10, and while it would be _more future-proof_ to …
=> Enforcing JDK 11 on release

src/main/java/org/codehaus/plexus/util/AbstractScanner.java
=> Don't ignore valid SCM files

src/main/java/org/codehaus/plexus/util/xml/pull/MXParser.java, src/test/java/org/codehaus/plexus/util/xml/pull/MXParserTest.java, src/test/resources/xml/test-entities-dos.xml, src/test/resources/xml/test-entities-in-attr-dos.xml, src/test/resources/xml/test-entities-in-attr.xml, src/test/resources/xml/test-entities.xml
* #163 - new case:  Don't assume UTF8 as default, to allow parsing from String.
* #194 - Incorrect getText() after parsing the DOCDECL section.
=> Fixed regressions: #163 and #194

src/main/java/org/codehaus/plexus/util/xml/pull/MXParser.java, src/test/java/org/codehaus/plexus/util/xml/pull/MXParserTest.java
Rebased and fixes #121 #122 and #124
=> MXParser fixes

pom.xml, src/test/java/org/codehaus/plexus/util/introspection/ReflectionValueExtractorTest.java
It only one class was used from this project.
This dependency takes much old stuff like maven 2
=> Get rid maven-plugin-testing-harness from dependency

src/main/java/org/codehaus/plexus/util/StringUtils.java, src/test/java/org/codehaus/plexus/util/StringUtilsTest.java
=> isEmpty(String) must not return false for whitespace-only values

src/main/java/org/codehaus/plexus/util/xml/Xpp3DomUtils.java
methods in StringUtils
This closes #215
=> Deprecate isEmpty(String) and isNotEmpty(String) in favour of same named

src/main/java/org/codehaus/plexus/util/xml/Xpp3DomUtils.java, src/test/java/org/codehaus/plexus/util/xml/Xpp3DomUtilsTest.java
=> Don't overwrite blank (but non-empty) dominant values during mergeXpp3Dom

src/main/java/org/codehaus/plexus/util/xml/Xpp3DomUtils.java, src/test/java/org/codehaus/plexus/util/xml/Xpp3DomUtilsTest.java
=> Always preserve dominant node value (even if empty)

src/main/java/org/codehaus/plexus/util/FileUtils.java
This PR spares code lines and potentially improves the performance of reading and writing files by using the new single-shot instructions of Java NIO available since Java 7 instead of the previous loops and readers/writers. There is no need to do this in custom code anymore as the JRE potentially knows the best way to do the job.
=> Reading and writing files using Java NIO

src/main/java/org/codehaus/plexus/util/xml/pull/MXParser.java, src/test/java/org/codehaus/plexus/util/xml/pull/MXParserTest.java
This would have to be back ported to maven 4, in light of #236
=> Fix reading comments with UTF chars (fixes #238)

README.md, pom.xml, src/site/markdown/index.md
relates to https://github.com/codehaus-plexus/plexus-xml/pull/24
=> downgrade plexus-xml from 4 to 3: keep Maven 3 compatibility

src/main/java/org/codehaus/plexus/util/MatchPattern.java, src/main/java/org/codehaus/plexus/util/MatchPatterns.java, src/main/java/org/codehaus/plexus/util/SelectorUtils.java, src/test/java/org/codehaus/plexus/util/MatchPatternTest.java, src/test/java/org/codehaus/plexus/util/MatchPatternsTest.java, src/test/java/org/codehaus/plexus/util/SelectorUtilsTest.java
Fix for #276 and #279 on V4
This change:
- Adds a public String source() method to MatchPattern to return the "source" instance value.
- Makes public MatchPattern method static String[] tokenizePathToString(String path, String separator)
- Adds public List sources() method to MatchPatterns that to return a list of MatchPattern.source() for each enclosed pattern.
- Makes public SelectorUtils static boolean isAntPrefixedPattern() method
- Makes public SelectorUtils static boolean isRegexPrefixedPattern() method
- Adds a SelectorUtils public static String extractPattern(final string pattern, final String separator) method to extract a simplified pattern without the Ant or Regex prefix and with the Ant path modified by a call to toOSRelatedPath to ensure that it is properly formatted.
=> V4 changes to make external usage easier

pom.xml, src/main/java/org/codehaus/plexus/util/MatchPattern.java, src/main/java/org/codehaus/plexus/util/MatchPatterns.java, src/main/java/org/codehaus/plexus/util/SelectorUtils.java, src/test/java/org/codehaus/plexus/util/MatchPatternTest.java, src/test/java/org/codehaus/plexus/util/MatchPatternsTest.java, src/test/java/org/codehaus/plexus/util/SelectorUtilsTest.java
Fix for #276 and #279 on V3
This change:
- Adds a public String source() method to MatchPattern to return the "source" instance value.
- Makes public MatchPattern method static String[] tokenizePathToString(String path, String separator)
- Adds public List<String> sources() method to MatchPatterns that to return a list of MatchPattern.source() for each enclosed pattern.
- Makes public SelectorUtils static boolean isAntPrefixedPattern() method
- Makes public SelectorUtils static boolean isRegexPrefixedPattern() method
- Adds a SelectorUtils public static String extractPattern(final string pattern, final String separator) method to extract a simplified pattern without the Ant or Regex prefix and with the Ant path modified by a call to toOSRelatedPath to ensure that it is properly formatted.
=> V3 changes to make external usage easier
